ramzy@ramzy:~/robot_urdf$ rosrun rosserial_python serial_node.py /dev/ttyACM0 _baud:=115200
[INFO] [1683505925.642948, 0.000000]: ROS Serial Python Node
[INFO] [1683505925.661089, 34.001000]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1683505927.778860, 36.105000]: Requesting topics...
[INFO] [1683505927.837971, 36.161000]: Note: subscribe buffer size is 280 bytes
[INFO] [1683505927.845062, 36.165000]: Setup subscriber on joint_states [sensor_msgs/JointState]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 537, in write
[WARN] [1683505976.694018, 83.107000]: Last read step: data checksum
    n = os.write(self.fd, d)
OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[WARN] [1683505976.713244, 83.175000]: Run loop error: [Errno 5] Input/output error
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_python/SerialClient.py", line 786, in processWriteQueue
[WARN] [1683505976.718790, 83.194000]: Unexpected Error: <class 'termios.error'>
    self._send(topic, msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_python/SerialClient.py", line 770, in _send
    self._write(self.header + self.protocol_ver + length_bytes + length_checksum_bytes + topic_bytes + msg_bytes + msg_checksum_bytes)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosserial_python/SerialClient.py", line 749, in _write
    self.port.write(data)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 571, in write
    raise SerialException('write failed: {}'.format(e))
serial.serialutil.SerialException: write failed: [Errno 19] No such device

